name: Generate and Download Artifacts

on:
  # push:
  #   branches: [main]
  workflow_dispatch:
    

jobs:
  generate-and-upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate test report
        run: echo "Generate the test report from generate-and-upload-artifact job" > report.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.txt

  download-artifact:
    runs-on: ubuntu-latest
    needs: generate-and-upload-artifact

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-report

      - name: Print artifact contents
        run: cat report.txt
