name: Deploy After Tests

on:
  workflow_run:
    workflows:
      - Run Tests
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Deployment Step
        run: echo "Tests passed. Deploying application..."

  failed-message:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion != 'success'

    steps:
      - name: Failure Message
        run: echo "Tests failed. Deployment skipped."