name: Test Secrets

on:
  push:
    branches: [main]

jobs:
  secrets-test:
    runs-on: ubuntu-latest

    steps:
      - name: Print secrets existence
        run: echo "The secrets is set - ${{ secrets.MY_SECRETS_MESSAGE != '' }}"

      - name: Print secrets value
        run: echo "The secret is - ${{ secrets.MY_SECRETS_MESSAGE }}"
