name: Test Secrets

on:
  push:
    branches: [main]

jobs:
  secrets-test:
    runs-on: ubuntu-latest

    steps:
      - name: Print secrets existence
        run: echo "The secrets is set - ${{ secrets.MY_SECRET_MESSAGE != '' }}"

      - name: Print secrets value
        run: echo "The secret is - ${{ secrets.MY_SECRET_MESSAGE }}"

  env-secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print secrets as env
        env:
          MY_SECRET: ${{secrets.MY_SECRET_MESSAGE}}
        run: |
          run: echo "The envvironment variable access secret is - ${ MY_SECRET }"
          
